FROM httpd:2.4
LABEL maintainer="Austin West awest1339"

ARG MS_WEB_METADATA_FIELDS="['Submitter Name', 'Submission Description', 'Submitter Email', 'Submitter Organization', 'Submitter Phone']"
ARG MS_WEB_TAGS="['Malware', 'Benign']"
ARG MS_USE_SSL=true
ARG MS_HTTP_PORT=80
ARG MS_HTTPS_PORT=443
ARG MS_API_LOC=https://msrest:8080
ARG apache_cert_folder_root=/usr/local/apache2/certs
ARG webserver_cert_file=msweb.crt
ARG webserver_key_file=msweb.key

ENV MS_WEB_TAGS=${MS_WEB_TAGS}
ENV MS_WEB_METADATA_FIELDS=${MS_WEB_METADATA_FIELDS}
ENV MS_API_LOC=${MS_API_LOC}
ARG MS_USE_SSL=${MS_USE_SSL}

# Set the locale
RUN apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN export LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

# Copy in required files
COPY . /opt/multiscanner

# Add Prereqs: Python3, mod_wsgi, etc.
RUN apt-get install -y --no-install-recommends \
        locales \
        python3 \
        python3-pip \
        python3-dev \
        curl \
        git \
        build-essential \
        libpq-dev \
        # OPENSSL_VERSION is set in the httpd Dockerfile
        libssl-dev=$OPENSSL_VERSION \
        libfuzzy-dev libffi-dev libjpeg-dev \
    && rm -rf /var/lib/apt/lists/* \
    && cd /usr/bin \
    && ln -s python3 python \
    && ln -s pip3 pip \
    && pip install --upgrade pip setuptools mod_wsgi \
    && mod_wsgi-express install-module \
    && cd /opt/multiscanner \
    && pip install .

# Add confd
ADD https://github.com/kelseyhightower/confd/releases/download/v0.14.0/confd-0.14.0-linux-amd64 /usr/local/bin/confd
RUN chmod +x /usr/local/bin/confd \
    && mkdir -p /etc/confd/conf.d /etc/confd/templates

# Configure Apache, install MultiScanner
# Put files in the right place for confd
RUN mv /opt/multiscanner/docker/distributed/*.toml /etc/confd/conf.d \
    && mv /opt/multiscanner/docker/distributed/*.tmpl /etc/confd/templates \
    # Create web log directory
    && mkdir /var/log/mscanweb \
    # Create and use a mod_wsgi run directory
    && mkdir /var/run/wsgi \
    # Move bootstrap script because permissions
    && mv /opt/multiscanner/docker/distributed/mscan_web.sh /opt \
    # TODO: Tell Apache where mod_wsgi is
    #&& MOD_WSGI_LOCATION="/usr/local/lib/python3.4/dist-packages/mod_wsgi/server/mod_wsgi-py34.cpython-34m.so" \
    #&& sed -i -r "s;\[\[ mod_wsgi_system_module \]\];$MOD_WSGI_LOCATION;g" /usr/local/apache2/conf/httpd.conf \
    # Install MultiScanner
    && /opt/multiscanner/install.sh


RUN MOD_WSGI_LOCATION=$(mod_wsgi-express module-config | grep wsgi_module | cut -d '"' -f2) \
    confd -onetime -backend env

RUN cat /opt/multiscanner/docker/distributed/mscan_web.conf

RUN cat /opt/multiscanner/docker/distributed/mscan_web.conf >> /usr/local/apache2/conf/httpd.conf \
    && echo "WSGISocketPrefix /var/run/wsgi" >> /usr/local/apache2/conf/httpd.conf \
    && rm /opt/multiscanner/docker/distributed/mscan_web.conf

# Start Apache
EXPOSE $MS_HTTP_PORT $MS_HTTPS_PORT
ENTRYPOINT ["/opt/mscan_web.sh"]
CMD ["httpd-foreground"]
