FROM httpd:2.4
LABEL maintainer="Austin West awest1339"

ARG MS_API_CORS_REGEX=https?://(localhost|msweb)
ARG MS_USE_SSL=true
ARG MS_API_PORT=8080
ARG MS_UPLOAD_DIR=/mnt/samples
ARG apache_cert_folder_root=/usr/local/apache2
ARG restserver_cert_file=msrest.crt
ARG restserver_key_file=msrest.key
ARG mod_ssl_system_module=/usr/lib/apache2/modules/mod_ssl.so

# Add Prereqs: Python3, mod_wsgi, etc.
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-dev \
        curl \
        git \
        build-essential \
        libpq-dev \
        # OPENSSL_VERSION is set in the httpd Dockerfile
        libssl-dev=$OPENSSL_VERSION \
    && rm -rf /var/lib/apt/lists/* \
    && cd /usr/bin \
    && ln -s python3 python \
    && ln -s pip3 pip \
    && pip install --upgrade pip setuptools mod_wsgi \
    && mod_wsgi-express install-module

# Add confd
ADD https://github.com/kelseyhightower/confd/releases/download/v0.14.0/confd-0.14.0-linux-amd64 /usr/local/bin/confd
RUN chmod +x /usr/local/bin/confd \
    && mkdir -p /etc/confd/conf.d /etc/confd/templates

# Copy in required files
COPY . /opt/multiscanner

# Configure Apache, install MultiScanner
RUN mkdir /var/log/mscanrest \
    # Create and use a mod_wsgi run directory
    && mkdir /var/run/wsgi \
    # Move bootstrap script because permissions
    && mv /opt/multiscanner/docker/distributed/mscan_rest.sh /opt \
    # Install MultiScanner
    && /opt/multiscanner/install.sh \
    # Tell Apache where mod_wsgi is
    # Enable the rewrite module (needed for CORS)
    && sed -i 's/#LoadModule rewrite_module/LoadModule rewrite_module/' /usr/local/apache2/conf/httpd.conf \
    # Put files in the right place for confd
    && mv /opt/multiscanner/docker/distributed/*.toml /etc/confd/conf.d \
    && rm /etc/confd/conf.d/mscan_web.toml \
    && mv /opt/multiscanner/docker/distributed/*.ini.tmpl /etc/confd/templates \
    && mv /opt/multiscanner/docker/distributed/mscan_rest.conf.tmpl /etc/confd/templates

RUN MOD_WSGI_LOCATION=$(mod_wsgi-express module-config | grep wsgi_module | cut -d '"' -f2) \
    confd -onetime -backend env

RUN cat /opt/multiscanner/docker/distributed/mscan_rest.conf
#RUN cat /usr/local/apache2/conf/httpd.conf

RUN cat /opt/multiscanner/docker/distributed/mscan_rest.conf >> /usr/local/apache2/conf/httpd.conf \
    && echo "WSGISocketPrefix /var/run/wsgi" >> /usr/local/apache2/conf/httpd.conf \
    && rm /opt/multiscanner/docker/distributed/mscan_rest.conf

RUN sed -i -r "s/Listen 80/Listen $MS_API_PORT/" /usr/local/apache2/conf/httpd.conf

RUN mkdir $MS_UPLOAD_DIR
RUN chown -R daemon:daemon /opt/multiscanner
RUN chown -R daemon:daemon $MS_UPLOAD_DIR

# Start Apache
EXPOSE $MS_API_PORT

CMD ["httpd-foreground"]
